### ISSUE TITLE
Problem with German Umlauts

### ISSUE THREAD

**Issue by trockenasche** [Avedo/Cubify#10]
when I using words with German Umlauts (Ä,Ö,Ü) i'm getting this error:

```
Traceback (most recent call last):
  File "cubify.py", line 687, in <module>
    main(sys.argv[1:])
  File "cubify.py", line 684, in main
    cubify.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "cubify.py", line 337, in effect
    (blockHeight - boxHeight) / 15 * 0.75, self.sideOneTextColor, self.sideOneBgColor, sideOneLayer)
  File "cubify.py", line 567, in formatTextBlock
    self.formatText(x, y + stepY * fontSize * 1.2, text, fontColor, bgColor, textItem)
  File "cubify.py", line 577, in formatText
    self.createTspan(text, fontColor, parent)
  File "cubify.py", line 674, in createTspan
    tspan.text = text
  File "lxml.etree.pyx", line 821, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:32944)
  File "apihelpers.pxi", line 645, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:15265)
  File "apihelpers.pxi", line 1242, in lxml.etree._utf8 (src/lxml/lxml.etree.c:19848)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes
```

Inkscape version 0.91 with Windows 7 x64

**Comment by Phidelux** [comment]
I will have a look at it.

**Comment by trockenasche** [comment]
any news?
